package de.rafaelbeckmann.hvkclient.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


// New generated HvK Theme from https://material-foundation.github.io/material-theme-builder/
val primaryLight = Color(0xFF784F83)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFBD7FF)
val onPrimaryContainerLight = Color(0xFF5E3869)
val secondaryLight = Color(0xFF575992)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE1E0FF)
val onSecondaryContainerLight = Color(0xFF404178)
val tertiaryLight = Color(0xFF824C76)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F1)
val onTertiaryContainerLight = Color(0xFF68355D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF7FB)
val onBackgroundLight = Color(0xFF1F1A1F)
val surfaceLight = Color(0xFFFFF7FB)
val onSurfaceLight = Color(0xFF1F1A1F)
val surfaceVariantLight = Color(0xFFEBDFE9)
val onSurfaceVariantLight = Color(0xFF4C444C)
val outlineLight = Color(0xFF7E747D)
val outlineVariantLight = Color(0xFFCFC3CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF8EEF5)
val inversePrimaryLight = Color(0xFFE7B6F1)
val surfaceDimLight = Color(0xFFE1D7DE)
val surfaceBrightLight = Color(0xFFFFF7FB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF1F8)
val surfaceContainerLight = Color(0xFFF5EBF2)
val surfaceContainerHighLight = Color(0xFFF0E5ED)
val surfaceContainerHighestLight = Color(0xFFEAE0E7)

val primaryDark = Color(0xFFE7B6F1)
val onPrimaryDark = Color(0xFF462151)
val primaryContainerDark = Color(0xFF5E3869)
val onPrimaryContainerDark = Color(0xFFFBD7FF)
val secondaryDark = Color(0xFFC0C1FF)
val onSecondaryDark = Color(0xFF292A60)
val secondaryContainerDark = Color(0xFF404178)
val onSecondaryContainerDark = Color(0xFFE1E0FF)
val tertiaryDark = Color(0xFFF5B2E2)
val onTertiaryDark = Color(0xFF4E1E45)
val tertiaryContainerDark = Color(0xFF68355D)
val onTertiaryContainerDark = Color(0xFFFFD7F1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFEAE0E7)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFEAE0E7)
val surfaceVariantDark = Color(0xFF4C444C)
val onSurfaceVariantDark = Color(0xFFCFC3CD)
val outlineDark = Color(0xFF988E97)
val outlineVariantDark = Color(0xFF4C444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE0E7)
val inverseOnSurfaceDark = Color(0xFF342F34)
val inversePrimaryDark = Color(0xFF784F83)
val surfaceDimDark = Color(0xFF161217)
val surfaceBrightDark = Color(0xFF3D373D)
val surfaceContainerLowestDark = Color(0xFF110D12)
val surfaceContainerLowDark = Color(0xFF1F1A1F)
val surfaceContainerDark = Color(0xFF231E23)
val surfaceContainerHighDark = Color(0xFF2E282E)
val surfaceContainerHighestDark = Color(0xFF393339)